version: '3.8'
services:
  cdp4-database-community-edition:
    image: rheagroup/cdp4-database-community-edition:latest
    hostname: cdp4-postgresql
    command: postgres -c max_locks_per_transaction=1024
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    networks:
      - docker-internal
    restart: always
    expose:
      - '5432'
    volumes:
      - cdpdbvolume96:/var/lib/postgresql/data
      - cdpdblogs96:/logs

  cdp4_webservices:
    hostname: cdp4-webservices
    image: rheagroup/cdp4-services-community-edition:latest
    restart: always
    networks:
      - docker-internal
      - internet
          # aliases:
          #   - cdp4-webservices
    depends_on:
      - cdp4-database-community-edition
    ports:
      - "5000:5000"
    expose:
      - '5000'
    volumes:
      - cdpwslogs:/app/logs
      - cdpwsstorage:/app/storage
      - cdpwsupload:/app/upload
networks:
  docker-internal:
    driver: bridge
    internal: true
  internet:
    driver: bridge

volumes:
  cdpdbvolume96:
  cdpdblogs96:
  cdpwslogs:
  cdpwsstorage:
  cdpwsupload:
